Feature/ot183 35
alkemyTech/OT183-server pull request #16
Opened 2022-04-19 10:20 UTC by julian955

2022-04-19 11:18 UTC, turcoamado requested changes

2022-04-19 11:18 UTC, turcoamado commented on src/main/java/com/alkemy/ong/mapper/UserMapper.java
> +        for (User entity: entityList) {
Para esto tambien podrias haber utilizado una expresion lambda, quedaria algo asi:
```
entityList.foreach{ entity -> 
    dtoList.add(userEntity2DTO(entity); 
}
```
Probalo primero

2022-04-19 11:18 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +@RequestMapping("user")
esto deberia ser: /users

2022-04-19 11:18 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(userList);
El estado http deberia ser un OK en lugar de un created, porque no se esta creando nada sino que consultamos algo nada mas.
Estaria bueno tener en cuenta que sucede si la lista esta vacia. Y en ese caso enviar un mensaje indicandolo

2022-04-20 02:26 UTC, julian955 commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(userList);
ya arregle los archivos y agregue la excepcion al metodo para que tire error en caso de ser nula la lista

2022-04-20 21:03 UTC, turcoamado requested changes
El PR esta bien, pero chequeate antes de mergear el tema del handler de errores y demas, porque ya hay algo de esto en develop, asi que hacete un merge para traerte esos cambios y fijate que es lo que podes tener de diferente, porque me figura como que la clases completas son nuevas.
Te deje un comentario en el mensaje que envias cunado la lista esta vacia, para que luego lo migres al properties y lo manejemos de esa manera

2022-04-20 21:03 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/imp/UserServiceImp.java
> +            throw new NullListException("there are no registered users");
Barbaro! Te voy a dejar aprobado el PR, pero esto luego hay que migrarlo al message.properties que trabajo Lucas para poner este tipo de mensajes que van hacia el usuario

2022-04-20 21:04 UTC, turcoamado approved these changes
Tene en cuenta el mensaje anterior antes de hacer el merge, te lo dejo aprobado

2022-04-20 23:38 UTC, merged