Feature/ot183-30
alkemyTech/OT183-server pull request #27
Opened 2022-04-22 14:55 UTC by lucasbravi2019

Tickets OT183-29 and OT183-30

2022-04-22 23:46 UTC, turcoamado requested changes
Muy bueno!! Te consulte algo que vi que eliminaste en SecurityConfig y te puse como evitar el hardcodeo de los http status, que estoy seguro lo sabes, es lo que se usa en los endpoints por ejemplo

2022-04-22 23:46 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/SecurityConfig.java
> -        http.authorizeRequests().antMatchers("/auth/login").permitAll().anyRequest().authenticated().and().httpBasic();
por que estas sacando este?

2022-04-22 23:46 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/MailServiceImpl.java
> +                    response.getStatusCode() != 200 &&
para evitar el hardcodear 200, 201, 202, etc podes hacer uso de HttpStatus.OK, HttpStatus.CREATED, HttpStatus.ACEPTED, etc

2022-04-23 00:12 UTC, lucasbravi2019 commented on src/main/java/com/alkemy/ong/security/SecurityConfig.java
> -        http.authorizeRequests().antMatchers("/auth/login").permitAll().anyRequest().authenticated().and().httpBasic();
Lo eliminé por error, ya lo corregí

2022-04-23 00:13 UTC, lucasbravi2019 commented on src/main/java/com/alkemy/ong/service/impl/MailServiceImpl.java
> +                    response.getStatusCode() != 200 &&
Si lo sé, pero me parecía que quedaba mas largo, aunque supongo que de esa manera ayuda a entenderlo mejor. Ahí lo arreglo.

2022-04-23 18:29 UTC, lucasbravi2019 commented on src/main/java/com/alkemy/ong/security/SecurityConfig.java
> -        http.authorizeRequests().antMatchers("/auth/login").permitAll().anyRequest().authenticated().and().httpBasic();
Perdón, en realidad si había un error al compilar con esa línea de codigo. Subí en una rama aparte un hotfix llamado GeneralErrors.

2022-04-24 18:15 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/MailServiceImpl.java
> +                    response.getStatusCode() != 200 &&
Si largo si, pero no es buena practica hardcodear nada, entones si ya tenemos algo que nos brinde esas constantes queda mejor tecnicamente

2022-04-24 18:16 UTC, turcoamado approved these changes

2022-04-24 18:30 UTC, lucasbravi2019 commented on src/main/java/com/alkemy/ong/service/impl/MailServiceImpl.java
> +                    response.getStatusCode() != 200 &&
Perfecto, de ahora en más lo voy a tener en cuenta.

2022-04-24 18:48 UTC, merged