Feature/ot183 50
alkemyTech/OT183-server pull request #33
Opened 2022-04-23 23:31 UTC by gabopereyra

<b>A saber:</b> en el controlador, se agrega la anotacion PreAuthorize("hasRole('ADMIN')"), la cual para las pruebas se comentó para evitar inconvenientes con la seguridad ya que al realizar este ticket la misma aún no se encuentra del todo implementada.

CREACIÓN DE LA ENTIDAD:
![imagen](https://user-images.githubusercontent.com/69758300/164949396-1d5da0f5-2dcd-4357-80aa-46541abe220d.png)
![imagen](https://user-images.githubusercontent.com/69758300/164949400-ae52bad0-fe9c-403d-a448-394f83b1492b.png)

Error si campo NAME es = null/vacio/cadena de espacios en blanco:
![imagen](https://user-images.githubusercontent.com/69758300/164949403-304326cc-714d-4ac4-8f2e-fd57844b1889.png)
![imagen](https://user-images.githubusercontent.com/69758300/164949404-e42d076f-e01d-47a4-92c6-de4594db0470.png)
![imagen](https://user-images.githubusercontent.com/69758300/164949405-53cf55c4-b133-495a-8af9-6b1468bfd885.png)

Error si campo “CONTENT” es null, vacio, o una cadena de espacios en blanco: (dado que los casos son similares a name se envía solo un ejemplo):
![imagen](https://user-images.githubusercontent.com/69758300/164949411-6375b82a-3af3-488b-b56d-e2af2f5bea36.png)

2022-04-24 18:54 UTC, turcoamado requested changes

2022-04-24 18:54 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/ActivityController.java
> +    @PreAuthorize("hasRole('ADMIN')")
Esto esta bien! Pero tambien se podria poner en el archivo donde se realiza la config de jwt, y cunado tengan que realizar la documentacion seguramente les convenga tenerlo alli

2022-04-24 18:54 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/ActivityController.java
> +    private ActivityServiceImpl service;
Aca tenes que inyectar la interface, y la interface es la que se encarga de implementar su propia implementacion

2022-04-24 18:54 UTC, turcoamado commented
Muy bueno que hayas probado todos los casos y adjuntado las imagenes!

2022-04-24 19:26 UTC, gabopereyra commented on src/main/java/com/alkemy/ong/controller/ActivityController.java
> +    @PreAuthorize("hasRole('ADMIN')")
Dale, si te consulto, esto seria definirlo en el archivo SecurityConfig? Por ejemplo, uno de los chicos coloco ahí para las rutas de los testimonios lo siguiente: 
http.authorizeRequests().antMatchers(HttpMethod.POST, "testimonials").hasRole("ADMIN");
Sería de esa manera? @turcoamado

2022-04-25 02:18 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/ActivityController.java
> +    @PreAuthorize("hasRole('ADMIN')")
claro, exactamente! @gabopereyra

2022-04-25 09:23 UTC, gabopereyra commented on src/main/java/com/alkemy/ong/controller/ActivityController.java
> +    @PreAuthorize("hasRole('ADMIN')")
Listo!

2022-04-25 09:24 UTC, gabopereyra commented on src/main/java/com/alkemy/ong/controller/ActivityController.java
> +    private ActivityServiceImpl service;
Listo!

2022-04-25 09:26 UTC, gabopereyra commented
@turcoamado, realizados los cambios marcados. Cuando le des el ok, mando el merge. Gracias!

2022-04-25 10:32 UTC, turcoamado approved these changes

2022-04-25 10:41 UTC, merged