Feature/ot183 45
alkemyTech/OT183-server pull request #34
Opened 2022-04-24 02:14 UTC by gabopereyra

<b>A saber:</b> en el controlador, se agrega la anotacion PreAuthorize("hasRole('ADMIN')"), la cual para las pruebas se comentó para evitar inconvenientes con la seguridad ya que al realizar este ticket la misma aún no se encuentra del todo implementada.
Se inyectan dos datos de prueba en base de datos, para permitir prueba (Activity y News).

<b>Busqueda con ID existente</b>
![imagen](https://user-images.githubusercontent.com/69758300/164952939-77b9ad9e-3548-4eca-9640-2504808a1927.png)
![imagen](https://user-images.githubusercontent.com/69758300/164952952-bf3f307f-4a39-4e68-84d5-099f55f247bd.png)
![imagen](https://user-images.githubusercontent.com/69758300/164953092-e23e51ef-6499-4e6b-b107-0e24d56c122d.png)

<b>Busqueda de un ID inexistente:</b>
![imagen](https://user-images.githubusercontent.com/69758300/164953047-211e997c-f251-44d4-b3e4-1581e6e8f506.png)

2022-04-24 19:01 UTC, turcoamado requested changes
Te hice los mismos comentarios que en otro de tus PRs, pero esta bien el endpoint.
Consulta, los archivos correspondientes a Activity (dto, services, controller) entiendo que estan porque saliste de la rama anterior, no suele ser una buena practica eso, intenta siempre salir desde develop con lo ultimo que haya alli, para evitar conflictos y re trabajo

2022-04-24 19:01 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/ActivityController.java
> +    private ActivityServiceImpl service;
Acordate que en los controladores inyectamos las interfaces de los servicios, luego la misma interface se encarga de implementar su implementacion

2022-04-24 19:01 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/ActivityController.java
> +    @PreAuthorize("hasRole('ADMIN')")
Te lo comente tambien en tu otro PR, esto esta bien hecho, pero se puede agregar en el archivo de config de jwt en lugar de en cada contrller. Es lo mismo, pero cuando realicen la documentacion les traera menos quilombos tenerlo alli (al menos esa fue la experiencia de uno de los grupos).
La otra ventaja de tenerlo todo en ese archivo es que se puede ver facilmente la accesibilidad que tiene cada endpoint por determinados roles

2022-04-24 19:29 UTC, gabopereyra commented on src/main/java/com/alkemy/ong/controller/ActivityController.java
> +    private ActivityServiceImpl service;
> Te hice los mismos comentarios que en otro de tus PRs, pero esta bien el endpoint. Consulta, los archivos correspondientes a Activity (dto, services, controller) entiendo que estan porque saliste de la rama anterior, no suele ser una buena practica eso, intenta siempre salir desde develop con lo ultimo que haya alli, para evitar conflictos y re trabajo

@turcoamado uy uy, posiblemente venia en piloto automatico, ni cuenta me di, mil gracias! Para corregirlo, y que quede limpio este PR, ¿elimino esos archivos?, ¿o bien genero una nueva rama donde la historia este limpia y no los tenga?

2022-04-25 02:20 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/ActivityController.java
> +    private ActivityServiceImpl service;
@gabopereyra no ahora ya esta, tenelo en cuenta para la proxima. Fijate de primero solucionar las cosas en el otro, mergea cuando este listo y seguis con este.
Podrias de todos modos trabajar en este y listo, pero vamos a intentar hacer las cosas lo mejor que podamos.

2022-04-25 09:28 UTC, gabopereyra commented on src/main/java/com/alkemy/ong/controller/ActivityController.java
> +    private ActivityServiceImpl service;
Dale dale, por supuesto que si, es la idea! Gracias por la correción!

2022-04-25 09:36 UTC, gabopereyra commented on src/main/java/com/alkemy/ong/controller/ActivityController.java
> +    @PreAuthorize("hasRole('ADMIN')")
Listo!

2022-04-25 10:34 UTC, turcoamado approved these changes

2022-04-25 10:43 UTC, merged