Feature/183 69 create members
alkemyTech/OT183-server pull request #37
Opened 2022-04-25 01:32 UTC by ianklebold

Buenas te dejo el create de members. Paso las pruebas de criterio de aceptacion minimas. 

- Permitir crear un miembro completo
- No permitir campo nulo o vacio y simbolos extraños en el nombre del miembro
- No permitir campos vacios y nulos en imagen

Comparto algunas capturas que logré sacar en postman.

**Creacion con exito**
![Prueba1Members](https://user-images.githubusercontent.com/56406481/165006333-51b70969-0a0d-433b-acaa-6e088b902583.png)

**Errores ** 
![Prueba2Members](https://user-images.githubusercontent.com/56406481/165006330-cd0333b9-1d10-4465-9a3e-3ce40753f778.png)

![Prueba3Members](https://user-images.githubusercontent.com/56406481/165006326-a955a41c-4584-4521-8c56-a2067128e087.png)

![Prueba4Members](https://user-images.githubusercontent.com/56406481/165006402-4d444edd-58cf-4707-b530-6be5f9993e00.png)

AVISO los errores en los mensajes de error ya han sido solucionados en el nuevo push.

2022-04-25 02:14 UTC, turcoamado requested changes
Mire unicamente los archivos correspondientes a lo que tenias que trabajar en este ticket, te deje algunos comentarios.

Si deciden refactorizar el proyecto y cambiar el nombre del package raiz esta bien, me parece innecesario pero si lo quieren realizar esta bien, solo que van a tener que laburar seguramente con los merge, porque van a tener conflictos, hay muchos PRs en curso y estan utilizando la estructura existente.

Una cosa mas, tenes subidos en el PR archivos de configuracion, esos no deberian estar

2022-04-25 02:14 UTC, turcoamado commented on Proyecto/src/main/java/com/alkemy/ong/controller/MemberController.java
> +@RequestMapping("/api/v1/members")
aca deberia ser simplemente /members

2022-04-25 02:14 UTC, turcoamado commented on Proyecto/src/main/java/com/alkemy/ong/controller/MemberController.java
> +    public ResponseEntity<?> createMember(@RequestBody MemberDTO memberDTO){
Te falta hacer uso de la annotation @Valid

2022-04-25 02:14 UTC, turcoamado commented on Proyecto/src/main/java/com/alkemy/ong/dto/builders/MemberBuilderPost.java
> +    public MemberBuilderPost setName(String name){
En lugar de hacer todos los setters y getters podes utilizsar las annotations de Lombok (tal cual se usan en la entidad). Lo mismo para el constructor

2022-04-25 02:14 UTC, turcoamado commented on Proyecto/src/main/java/com/alkemy/ong/service/impl/MemberServiceImpl.java
> +            mapperError("Error the name can't be empty",406),
Tanto para este como para los demas errores el mensaje deberia salir desde el properties, y para el numero podes hacer uso del http status (que estas usando en el siguiente parametro). Otra cosa, utilizaria el BAD_REQUEST en lugar del NOT_ACCEPTABLE

2022-04-25 02:14 UTC, turcoamado commented on Proyecto/src/main/java/com/alkemy/ong/service/impl/MemberServiceImpl.java
> +        String url = "/api/v1/members/"+memberSaved.getId();
Para que estas usando la url? No entendi eso, por que el dto tiene una url que indica la ruta que se consumio?

2022-04-26 18:18 UTC, ianklebold commented
Buenas acabo de enviar mis correcciones en un nuevo Push. Acabo de implementar @Valid. En el caso de los set y get como vos bien dijiste se puede hacer con lombok pero en este caso solo necesito setters y estos son metodos personalizados porque aplico el patron builder para crear el DTO lo mismo en el caso del constructor de la misma clase. Ya testee lo que hice y los nuevos cambios funcionan correctamente. Saludos!

2022-04-27 10:49 UTC, turcoamado requested changes
Bueno Ian, con lo que me comentas podriamos dejarlo asi a tu PR, sigo pensando que te la complicaste con el tema del builder pero esta bien de todos modos. Lo unico que si no entiendo es por que en el response le seteas la url, tampoco seria necesario, pero no es drama.

El unico problema es que no podemos mergear esto porque cambia toda la estructura del proyecto, como te habia dicho antes, y es un problema porque para corregirlo no te va a quedar otra que clonar el proyecto nuevamente y meter los cambios a mano, es tedioso, vas a tener que copiar y pegar en un nuevo PR solo las clases correspondientes a tu ticket, que si no me olvido ninguna son las siguientes:
**MemberController**
**MemberDTO**
**MemberBuilderPost
IMemberBuilder
PostMemberDTO
MemberServiceIml
MemberMapperPost**

2022-04-28 11:09 UTC, closed without merging