Feature/ot183 34
alkemyTech/OT183-server pull request #48
Opened 2022-04-27 17:56 UTC by celsobrc

**SUMMARY**
- Update user endpoint added for handle PATCH request
- Route security added

_Patch request without errors_
![image](https://user-images.githubusercontent.com/55297121/165588526-15f5af0d-a416-4033-810a-d619a01f3462.png)
![image](https://user-images.githubusercontent.com/55297121/165588616-abbc94bb-9149-4d14-8564-e401fb76edc6.png)
![image](https://user-images.githubusercontent.com/55297121/165588649-a739a3a9-4d23-4724-aeeb-a185972c664f.png)

_Invalid id in request path_
![image](https://user-images.githubusercontent.com/55297121/165588751-6c977771-2005-4137-a6c4-7c6551b1be35.png)

_Update with blank string_
![image](https://user-images.githubusercontent.com/55297121/165588863-585bbb20-6d01-4d27-8e33-436a35415a7e.png)

2022-04-28 11:06 UTC, turcoamado requested changes

2022-04-28 11:06 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +    public ResponseEntity<UserProfileDto> updateUser(@PathVariable Long id,@RequestBody Map<String, Object> updates ){
En lugar de utilizar un map deberias tener un dto, entonces vos recibis el dto, lo mapeas a entidad (debes crear un mapper tambien), persistis los cambios, y mapeas nuevamente de entidad a dto como haces en el service.

2022-04-28 11:06 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java
> +    public UserProfileDto updateUser(Long id, Map<String, Object> updates) {
Tecnicamente esto esta muy bien, me refiero al manejo de un map con la expresion lambda, pero conceptualmente deberias tener un DTO y no un map, tenes que crear un DTO para el request o utilizar uno existente, mapearlo a entity, realizar el update y luego mapearlo a DTO nuevamente como haces al final

2022-04-28 16:14 UTC, celsobrc reviewed
@turcoamado arregle lo solicitado. El mapeo lo hice directamente en el service porque me parece que llamar al mapper sería forzar el tema siendo que ya tengo la entidad pero si crees que es necesario lo cambiamos.

2022-04-28 16:14 UTC, celsobrc commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +    public ResponseEntity<UserProfileDto> updateUser(@PathVariable Long id,@RequestBody Map<String, Object> updates ){
Modificado

2022-04-28 16:15 UTC, celsobrc commented on src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java
> +    public UserProfileDto updateUser(Long id, Map<String, Object> updates) {
Modificado

2022-04-29 02:59 UTC, turcoamado approved these changes
Ahora si, genial! Con el tema del mapper es lo mismo, podes realizarlo dentro del service o crear una clase donde tengas los dos que corresponden a este caso ponele. Eso no recuerdo ahora como lo eligieron manejar, a mi me da lo mismo, sepan que tienen ambas formas. Por ahi cuando los services son muy complejos o largos se estila tenerlos por separado, mas alla de que haya que instanciar otra clase, el codigo queda un poco mas facil de leer

2022-04-29 11:43 UTC, merged