Feature/ot183-72
alkemyTech/OT183-server pull request #64
Opened 2022-05-02 14:59 UTC by lucasbravi2019

- User Seeder added
- Role Seeder added
- RoleNotFoundException and handler added
- Entities and repositories adapted
![Seed roles](https://user-images.githubusercontent.com/80082740/166256550-bdc64897-2316-413f-b7f7-f5a8699162e9.png)
![Seed users](https://user-images.githubusercontent.com/80082740/166256559-7f3efa01-dabf-4e61-9f63-187a7194f52d.png)

2022-05-02 20:25 UTC, turcoamado requested changes
Esta  bien, es valido lo que hiciste. Otra forma hubise sido llamar n veces a un metodo que sea createUser por ejemplo, en vez de hacer el for del final donde iteras 20 veces, y en ese create user le pasas todos los datos necesarios para la creacion de un usuario.

Lo que no entendi es el atributo _comments_, para que esta eso?

2022-05-02 20:25 UTC, turcoamado commented on src/main/java/com/alkemy/ong/seed/UserSeeder.java
> +                    .comments(null)
a que hace referencia el comments? No recuerdo que el modelo de User tenga que tener un atributo comments

2022-05-02 21:27 UTC, lucasbravi2019 commented on src/main/java/com/alkemy/ong/seed/UserSeeder.java
> +                    .comments(null)
![comments](https://user-images.githubusercontent.com/80082740/166330494-0461a676-50cc-4a4b-b6a8-1f942944807f.png)

2022-05-02 21:27 UTC, lucasbravi2019 commented on src/main/java/com/alkemy/ong/seed/UserSeeder.java
> +                    .comments(null)
Esa relación está en User

2022-05-02 22:02 UTC, lucasbravi2019 commented on src/main/java/com/alkemy/ong/seed/UserSeeder.java
> +                    .comments(null)
![Seed users](https://user-images.githubusercontent.com/80082740/166334419-79f415d0-ed2e-449a-982b-805277a74bf0.png)

Así queda con los nuevos cambios. Sigue igual, sólo hago minúsculas los emails.

2022-05-03 03:30 UTC, turcoamado approved these changes

2022-05-03 09:48 UTC, merged