Endpoint update activity added
alkemyTech/OT183-server pull request #67
Opened 2022-05-03 00:00 UTC by julian955

- Endpoint update activity added.
- Id validation added.
- Only admin user can use this endpoint.

![Activity Updated](https://user-images.githubusercontent.com/72110763/166344296-f7123da9-19e6-4db4-8ec7-d607478ab91b.jpg)
![Update Error](https://user-images.githubusercontent.com/72110763/166344300-b77db7de-3855-43ec-beed-b77d18fff616.jpg)

2022-05-03 03:34 UTC, turcoamado requested changes
Muy bueno la utilizacion de expresiones lambda! Te deje un solo comentario en el controller, que te falta una annotation, lo demas todo OK

2022-05-03 03:34 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/ActivityController.java
> +    public ResponseEntity<ActivityDto> updateActivity(@PathVariable Long id, @RequestBody ActivityDto activityDto){
Te falta hacer uso de la annotation @Valid

2022-05-04 00:02 UTC, julian955 commented on src/main/java/com/alkemy/ong/controller/ActivityController.java
> +    public ResponseEntity<ActivityDto> updateActivity(@PathVariable Long id, @RequestBody ActivityDto activityDto){
Ya la agregue, se me paso

2022-05-04 02:20 UTC, turcoamado approved these changes

2022-05-04 10:02 UTC, merged