EndPoint oganization/contactSocialAddresses/id
alkemyTech/OT183-server pull request #69
Opened 2022-05-03 01:48 UTC by MatiasGrando

Tarea 
COMO usuario administrador
QUIERO editar los campos de contacto a la Organización
PARA mostrar la información de la mejor manera posible. 
Criterios de aceptación:
Modificar modelo, repositorio y servicio para agregar las urls de redes sociales a una Organización. Se deberán agregar url de Facebook, Linkedin e Instagram

Summary 
-Se agregaron los campos facebook, instagram y linkedin al modelo Organization
-Se agrego un endPoint que recibe una id y un dto para actualizar los datos, el cual requiere auth "ADMIN"
-Se creo un dto para recibir los datos a actualizar
-Se actualizo el dto existente para recibir toda la informacion con los nuevos campos
-Se actualizo el service agregando la funcionalidad de actualizar la informacion
-Se aplico la deteccion de errores en el service

2022-05-03 03:49 UTC, turcoamado requested changes
Mati, lo que hiciste programaticamente esta bien, pero te excediste de lo que decia el ticket. Existe una tarea para poder modificar las urls de los perfiles, y en realidad hay que modificar el endpoint de datos publicos de la org, que esta pendiente hace como dos semanas (Es un ticket de Leo: https://alkemy-labs.atlassian.net/browse/OT183-37)

Si te parece, ya que estas hacelo, porque hiciste gran parte, seria en realidad crear el endpoint que dice alli y le agregas lo de las urls (que es este otro ticket: https://alkemy-labs.atlassian.net/browse/OT183-64 y lo tiene Julian)

En conclusion, podes hacer uno o varias de los siguientes puntos
- Dejar este unicamente con las cosas que pide el ticket que tomaste (sin la creacion del endpoint)
- Finalizar la tarea https://alkemy-labs.atlassian.net/browse/OT183-37 iniciada por Leo (podes mirar el PR que esta existente, solo que nunca mas hizo nada)
- Modificar el endpoint ademas para que puedan modificarse las urls de las redes sociales, previa charla con Julian que tiene el ticket asignado: https://alkemy-labs.atlassian.net/browse/OT183-64

2022-05-03 03:49 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/OrganizationController.java
> +            (@PathVariable Long id, @RequestBody OrganizationSocialAddressesDto dto){
Te estaria faltando la annotation @Valid

2022-05-04 14:37 UTC, MatiasGrando commented
Se creo la funcion Put
- Modifique el DTO- y repositorio del GET/public para devolver todos los datos (este lo toque con dudas porque es un codigo mas complejo como lo diseñaron la obtencion de la entidad y manejo del dto)
- Sobre la implementacion anterior habia  un dto organizationDetailsDto que no se usaba, ya que para el gets que muestra datos publicos tiene su propio dto, por ende decidi modificar parte del codigo para trabajar en ese Dto y no crear uno nuevo.

saque una funcionalidad que no se aplicaba nunca, no estaba en funcionamiento y no era requerida(para volver a aplicarla se deberia volver a crear otro dto y agregarlo nuevamente ese codigo)

Dudas: no se si era la mejor alternativa la que tome, o si era mejor dejar todo tal cual y armar un nuevo dto y usarlo.
Espero el feedback para luego saber si volver a restaurar el codigo y crear un nuevo dto o asi esta bien

2022-05-05 01:33 UTC, turcoamado approved these changes
Creo que lo resolviste bastante bien! Te deje un comentario nada mas en un DTO que me parece no se esta utilizando, o al menos no encontre una referencia. Te lo dejo como aprobado y si efectivamente no se usa borralo porfa.

2022-05-05 01:33 UTC, turcoamado commented on src/main/java/com/alkemy/ong/dto/OrganizationSocialAddressesDto.java
> +public class OrganizationSocialAddressesDto {
Este DTO no se esta usando mas verdad? Si no se utiliza boletealo nomas

2022-05-08 03:16 UTC, merged