Feature/ot183 57
alkemyTech/OT183-server pull request #75
Opened 2022-05-03 22:57 UTC by gabopereyra

<p>@turcoamado , desde el vamos: <b>PERDON</B>, veras que meti mil cambios, tuve problemas por varios lados, a continuacion paso a explicar algunas cosas de relevancia:</p>
<ul>
<li>Al igual que tickets anteriores, el endpoint fue probado sin seguridad (aun no indicada si ya esta finalizada la implementacion)</li>
<li><b>Entidad SLIDE:</b>, tuve que modificar de String a Integer el atributo position (en el ticket aparece "order" pero aca fue creado previamente como position y eso lo mantuve), esto respondia a que si queria obtener la maxima posicion no lo hacia en base a un numero sino a un String. Dado este cambio tuve que modificar todos los DTOs asociados, ya que los mismos trabajaban sobre un dato del tipo String.</li>
<li><b>Relacion entre SLIDE y ORGANIZATION:</b> Hubo que modificarla, ya que la manera en la que estaban planteadas generaba una excepcion (TransientObjectException) al querer guardarla, de alli los cambios que vas a encontrar en estas entidades.</li>
<li>El resto de los cambios fueron para poder lograr lo solicitado (conversion de base64 a imagen, obtener ultima posicion BD, etc)</li>
</ul>

<p>Hecho el preambulo, dejo las capturas de Postman:</p>
<ul><li><a href="https://user-images.githubusercontent.com/69758300/166585005-77b463be-f297-4eef-bf33-e3b9037278cc.png">Peticion con ID inexistente de organizacion</a></li>

<li><a href="https://user-images.githubusercontent.com/69758300/166585124-57918ae5-d503-4a26-8b0c-38d2b313bad3.png">Peticion Exitosa, <b>CON</b> orden</a></li>
<ul><li><a href="https://user-images.githubusercontent.com/69758300/166585366-1dfccf7b-5dcc-47c4-a704-4b72a755a0bb.png">Peticion SQL Slide</a></li>
<li><a href="https://user-images.githubusercontent.com/69758300/166585375-94a1e95f-11a4-4cd3-9588-fc520269c86f.png">Peticion SQL Organizacion</a></li>
</ul>
<li><a href="https://user-images.githubusercontent.com/69758300/166585554-4a8b564d-9a71-4dcf-b6ff-542a37d22c30.png">Peticion Exitosa, <b>SIN</b> orden (ver detalle que position ahora es 3, la max anterior era 2)</a></li>
<ul><li><a href="https://user-images.githubusercontent.com/69758300/166585573-53c7acad-8e11-4bd0-862b-d16c5bd75d23.png">Peticion SQL Slide</a></li>
</ul>

P.D: ahora aviso al grupo de los cambios vinculados a las entidades

2022-05-04 11:09 UTC, turcoamado requested changes
Gabo, muy bueno el PR. Esta bien el cambio de String a Integer para la position (podria haber sido int tambien), por lo que entiendo todos los cambios que eso conyeva en las demas clases.
Genial el tratamiento para las imagenes, la conversion en Base64.

Te deje solamente 2 comentarios, uno en la query, una pavada, poner el alias en ingles en lugar de espaniol. El otro en un DTO, creo que el constructor esta de mas, que lo cubris con una annotation de Lombok.
Fijate esas dos cosas y listo.

2022-05-04 11:09 UTC, turcoamado commented on src/main/java/com/alkemy/ong/dto/SlideDto.java
> +    public  SlideDto(String imageUrl, String text, Integer position, OrganizationDto organization) {
Este constructor estaria de mas, entiendo que lo tenes cubierto con la annotation @AllArgsConstructor. Sacalo y fijate por las dudas

2022-05-04 11:09 UTC, turcoamado commented on src/main/java/com/alkemy/ong/repository/SlideRepository.java
> +    @Query(value = "SELECT MAX(position) AS maximo FROM slides", nativeQuery = true)
Aca ponele maximum en lugar de maximo, para mantener el ingles

2022-05-04 11:56 UTC, gabopereyra commented on src/main/java/com/alkemy/ong/dto/SlideDto.java
> +    public  SlideDto(String imageUrl, String text, Integer position, OrganizationDto organization) {
Turco! El constructor lo sume porque el DTO tiene declarado un ID (quise reutilizar lo que ya habia), y la estructura que necesitaba para la logica armada, mi SlideDTO tenia que ir sin ID. 
Dejo imagen donde lo uso, y que me marca error si borro el constructor:
![imagen](https://user-images.githubusercontent.com/69758300/166676346-2dfef267-bc77-4312-ada4-bb2651df35db.png)

2022-05-04 11:56 UTC, gabopereyra commented on src/main/java/com/alkemy/ong/repository/SlideRepository.java
> +    @Query(value = "SELECT MAX(position) AS maximo FROM slides", nativeQuery = true)
Listo esto!

2022-05-05 01:00 UTC, turcoamado approved these changes

2022-05-05 01:00 UTC, turcoamado commented on src/main/java/com/alkemy/ong/dto/SlideDto.java
> +    public  SlideDto(String imageUrl, String text, Integer position, OrganizationDto organization) {
Ok entiendo, dejalo entonces por ahora y lo vemos mas adelante en todo caso, pero me parece raro, no deberia ser necesario especificar el constructor, seguramente se soluciona modificando algo en otro lado, pero no entremos en esos detalles ahora ya que es una pavada.

2022-05-05 01:45 UTC, merged