Feature/ot183-90
alkemyTech/OT183-server pull request #90
Opened 2022-05-11 06:16 UTC by lucasbravi2019

- Fixed JsonWebToken
- Users Endpoint Integration Test added
- Test utils added
- Application properties for tests added
![test](https://user-images.githubusercontent.com/80082740/167781400-e9063e90-bca6-43ac-9f9e-129bcd3c9349.png)

2022-05-11 11:04 UTC, turcoamado requested changes
Lucas los test estan muy bien! Genial que hayas hecho uso de la annotation @BeforeEach. Una cosa, el @Order() en este caso no seria necesario, ya que estamos probando test unitarios, quizas va a ser util si fuesen de integracion y necesitamos ejeccutar si o si uno antes de otro por algun cambio en la aplicacion.
No entendi por que comentaste todos los authorizeRequest para el rol ADMIN, esta totalmente sin seguridad ahora? Como lo estas haciendo funionar?

2022-05-11 12:37 UTC, lucasbravi2019 commented
> Lucas los test estan muy bien! Genial que hayas hecho uso de la annotation @beforeeach. Una cosa, el @order() en este caso no seria necesario, ya que estamos probando test unitarios, quizas va a ser util si fuesen de integracion y necesitamos ejeccutar si o si uno antes de otro por algun cambio en la aplicacion. No entendi por que comentaste todos los authorizeRequest para el rol ADMIN, esta totalmente sin seguridad ahora? Como lo estas haciendo funionar?

Los comenté por las dudas de haber roto algo, pero ahora agregue 
http.authorizeRequests().antMatchers("/**").hasAuthority("ADMIN");
Esto filtra todas las peticiones para que tengan el rol de ADMIN, por alguna razón, no filtraba las url como estaban antes. En los test y en postman recibo codigo 401 si no estoy logeado, 403 si el rol es USER y 200 si es ADMIN.

2022-05-12 03:36 UTC, turcoamado approved these changes
Como te deje comentado, tus tests estan bien, pero tenemos que resolver el tema de la security. Te voy a dejar aprobado el PR porque funciona lo que realizaste, pero es importante que podamos acomodar lo de la seguridad.
Entendi tambien lo del orden

2022-05-12 03:36 UTC, turcoamado commented on src/main/java/com/alkemy/ong/auth/config/SecurityConfig.java
> +        http.authorizeRequests().antMatchers("/**").hasAuthority("ADMIN");
Entendi lo que me dijiste a medias, con esto asumo que le estas metiendo a todo el rol de ADMIN, y por eso en los test te devuelve esos codigos. Tus tests estan bien, pero tenemos que resolver el tema de la security.

2022-05-12 11:28 UTC, merged